version: '^3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keateka
      - POSTGRES_PASSWORD=keateka123
      - POSTGRES_DB=keateka_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keateka_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - keateka_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://keateka:keateka123@postgres:5432/keateka_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - keateka_network

volumes:
  postgres_data:
  redis_data:

networks:
  keateka_network:
    driver: bridge
