"""initial migration

Revision ID: c1bb14995d5c
Revises:
Create Date: 2024-12-01 18:30:56.887872

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "c1bb14995d5c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
